### ISSUE TITLE
Not supporting schema_format = :sql in 4.0.0

### ISSUE THREAD

**Issue by egukin** [thuss/standalone-migrations#109]
After upgrading to 4.0.0, I can no longer generate my `structure.sql` file, because with `schema_format` set to `:sql` any task fails with this error:

```
$ rake db:migrate
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:182:in `structure_dump'
~/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:276:in `block (3 levels) in <top (required)>'
~/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:51:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:structure:dump
```

**Comment by twobitlabs** [comment]
@ywen any ideas? We haven't upgraded to 4.0.0 yet...

**Comment by ywen** [comment]
Sorry I was busy, will take a look tonight

**Comment by benmmurphy** [comment]
I use this to get it to work but it breaks other stuff so is not a good solution:

    require 'yaml'
    require 'tasks/standalone_migrations'
    StandaloneMigrations::Tasks.load_tasks

    ActiveRecord::Tasks::DatabaseTasks.database_configuration = Rails.application.config.database_configuration

    module StandaloneMigrations
      class Configurator
        def initialize(options = {})
          defaults = {
            :config       => "db/config.yml",
            :migrate_dir  => "db/migrate",
            :seeds        => "db/seeds.rb",
            :schema       => "db/schema.rb"
          }
          @options = load_from_file(defaults.dup) || defaults.merge(options)
          ENV['SCHEMA'] = ENV['SCHEMA'] || File.expand_path(schema)


          # HACK
          ENV['DB_STRUCTURE'] = File.expand_path(@options[:structure])


          # HACK
        end
        def load_from_file(defaults)
          return nil unless File.exists? configuration_file
          config = YAML.load( ERB.new(IO.read(configuration_file)).result )
          {
            :config       => config["config"] ? config["config"]["database"] : defaults[:config],
            :migrate_dir  => (config["db"] || {})["migrate"] || defaults[:migrate_dir],
            :seeds        => (config["db"] || {})["seeds"] || defaults[:seeds],
            :schema       => (config["db"] || {})["schema"] || defaults[:schema],
            #HACK
            :structure       => (config["db"] || {})["structure"] || defaults[:structure]
            #HACK
          }
        end
      end
    end

    ActiveRecord::Base.schema_format = :sql

**Comment by ywen** [comment]
I can't reproduce the error. Here is my `Rakefile`

```ruby
#!/usr/bin/env rake
require "bundler/gem_tasks"
require_relative "lib/my_gem"
require 'standalone_migrations'
ActiveRecord::Base.schema_format = :sql
StandaloneMigrations::Tasks.load_tasks
Dir["#{File.dirname(__FILE__)}/tasks/**/*.rake"].each {|f| load f}
```

The `db/structure.sql` is generated successfully and can be used for importing into another DB.

Could you share your config?

**Comment by benmmurphy** [comment]
ywen: i see there are two problems.

1) when using multiple databases the structure.sql location does not seem to be configurable so all the databases write the file to the same location

2) in later versions of rails (4.2.1?) you receive the error 'NoMethodError: undefined method `[]' for nil:NilClass' when trying to dump the structure of the database. I'm not sure when standalone migrations was broken by the rails changes.

**Comment by benmmurphy** [comment]
you should be able to reproduce the nil class problem with a normal config and these Gemfile/Gemfile.lock files.

    # A sample Gemfile
    source "https://rubygems.org"
    gem "standalone_migrations"
    gem "pg"

-----
    GEM
      remote: https://rubygems.org/
      specs:
        actionpack (4.2.1)
          actionview (= 4.2.1)
          activesupport (= 4.2.1)
          rack (~> 1.6)
          rack-test (~> 0.6.2)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.1)
        actionview (4.2.1)
          activesupport (= 4.2.1)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.1)
        activemodel (4.2.1)
          activesupport (= 4.2.1)
          builder (~> 3.1)
        activerecord (4.2.1)
          activemodel (= 4.2.1)
          activesupport (= 4.2.1)
          arel (~> 6.0)
        activesupport (4.2.1)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        arel (6.0.0)
        builder (3.2.2)
        erubis (2.7.0)
        i18n (0.7.0)
        json (1.8.2)
        loofah (2.0.1)
          nokogiri (>= 1.5.9)
        mini_portile (0.6.2)
        minitest (5.5.1)
        nokogiri (1.6.6.2)
          mini_portile (~> 0.6.0)
        pg (0.18.1)
        rack (1.6.0)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails-deprecated_sanitizer (1.0.3)
          activesupport (>= 4.2.0.alpha)
        rails-dom-testing (1.0.6)
          activesupport (>= 4.2.0.beta, < 5.0)
          nokogiri (~> 1.6.0)
          rails-deprecated_sanitizer (>= 1.0.1)
        rails-html-sanitizer (1.0.2)
          loofah (~> 2.0)
        railties (4.2.1)
          actionpack (= 4.2.1)
          activesupport (= 4.2.1)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (10.4.2)
        standalone_migrations (4.0.0)
          activerecord (~> 4.2.0)
          railties (~> 4.2.0)
          rake (~> 10.0)
        thor (0.19.1)
        thread_safe (0.3.5)
        tzinfo (1.2.2)
          thread_safe (~> 0.1)

    PLATFORMS
      ruby

    DEPENDENCIES
      pg
      standalone_migrations

**Comment by ywen** [comment]
@benmmurphy Could you paste your Rakefile or whichever file you set 

```ruby
ActiveRecord::Base.schema_format = :sql
```

Are you using `db/config.yml` to config your DB or using `DATABASE_URL` env variable?

**Comment by benmmurphy** [comment]
Rakefile

    require 'standalone_migrations'
    ActiveRecord::Base.schema_format = :sql
    StandaloneMigrations::Tasks.load_tasks

----
For the multiple database configuration:
.xxxx.standalone_migrations

    db:
        seeds: xxxx_db/seeds.rb
        migrate: xxxx_db/migrate
        schema: xxxx_db/schema.rb
        structure: xxxx_db/schema.sql
    config:
        database: xxxx_db/config.yml

----
Command

    rake DATABASE=development DB=sonar db:structure:dump

But I also get the same problem with the single database configuration:

    rake  db:structure:dump

**Comment by ywen** [comment]
Fixed in #110

**Comment by twobitlabs** [comment]
Released version 4.0.1, thanks @ywen for all your work on that!
