### ISSUE TITLE
rake db:reset not working in 1.0.1

### ISSUE THREAD

**Issue by febuiles** [thuss/standalone-migrations#32]
When trying to run `rake db:reset` in 1.0.1, I get the following error:

```
 rake aborted!
 undefined method `load_seed' for "fake_app":String

 Tasks: TOP => db:reset => db:setup => db:seed
 (See full trace by running task with --trace)
```

Maybe `#load_seed` should be overriden to be a no-op?
